version: '3.8'
services:
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --save 60 1
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  bot:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - FILES_PATH=./files
      - SHOP_ID=${SHOP_ID}
      - REDIS_HOST=${SERVER_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

volumes:
  redis-data:
