debug: true

telegram:
  token: ${AUTH_TOKEN:6590818583:AAEp-5ATOUwO_nLb3qm7fsz9UTKKk5nD2h8}
  botName: wine_art_bot

qr:
  url:
    page: https://huuudrich.github.io/wine_art_approve_page/?number

shop:
  provider:
    token: ${SHOP_ID:381764678:TEST:86436}

spring:
  data:
    redis:
      host: ${SERVER_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:default}

messages:
  start:
    command:
      message: |
        <b>Здравствуйте!</b>
        
        Это студия современной живописи <b>Wine&Art</b>, мы создали этот бот для того чтобы вы смогли приобрести электронный подарочный сертификат в любое время суток👏🏻
        Электронный сертификат можно не распечатывать, а просто предъявить в электронном виде.
        Если вам нужен бумажный вариант или у вас возникнут вопросы, то просьба обратиться к администратору: @wine_art_sakh.
        
        Наша группа: @wineartsakh
  payment:
    command:
      message: Пожалуйста укажите сумму покупки сертификата от 2500 до 10.000 рублей
