messages:
  start:
    command:
      message: |
        <b>Здравствуйте!</b>
        
        Это студия современной живописи <b>Wine&Art</b>, мы создали этот бот для того чтобы вы смогли приобрести электронный подарочный сертификат в любое время суток👏🏻
        Электронный сертификат можно не распечатывать, а просто предъявить в электронном виде.
        Если вам нужен бумажный вариант или у вас возникнут вопросы, то просьба обратиться к администратору: @wine_art_sakh.
        
        Наша группа: @wineartsakh
  payment:
    command:
      message: Пожалуйста укажите сумму покупки сертификата от 2500 до 10.000 рублей
